[env]
TERM = "alacritty"


[[hints.enabled]]  # see https://github.com/alacritty/alacritty/issues/5246
command = ""
hyperlinks = true
mouse.enabled = false


[[keyboard.bindings]]
key = "i"
mods = "Control"
chars = "\u001e"  # 0x1e = 30 = <C-^> = Record Separator


[window]          # Fixes MacOS Mission Control being laggy,
opacity = 0.9999  # see https://github.com/alacritty/alacritty/issues/4474

[window.padding]
x = 0
y = 0


[font]
size = 9.4
# size = 8.0  # x150 on Windows

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"


[colors.primary]
background = "#111111"
foreground = "#d8d8d8"

[colors.normal]
black   = "#000000"
red     = "#ff5555"
green   = "#88ffaa"
yellow  = "#eeff88"
blue    = "#88eeff"
magenta = "#ff77cc"
cyan    = "#88eeff"
white   = "#ffffff"

[colors.bright]
black   = "#555555"
red     = "#ff5555"
green   = "#88ffaa"
yellow  = "#eeff88"
blue    = "#88eeff"
magenta = "#ff79c6"
cyan    = "#88eeff"
white   = "#ffffff"
